baseURL = '/'
languageCode = 'en-us'
title = 'JLK'
theme = 'jlk'
enableGitInfo = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false

[params]
description = "Thoughts and compilations"
listDataFormat = '2 Jan 2006'

[[params.menu]]
name = "home"
url = "/"

[menus]
    [[menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = '10'
    [[menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = '20'
    
