baseURL = '/'
languageCode = 'en-us'
title = 'JLK'
theme = 'lugo'
enableGitInfo = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false

[params]
description = "Fun things to think about"
listDataFormat = '2 Jan 2006'

homeIntroContent = """
You've reached the personal website of Julian Lindsay-Kaufman... Prepare for your imminent doom! Or, enjoy some (hopefully helpful) thoughts and compilations.
"""

[[params.menu]]
name = "home"
url = "/"

[menus]
    [[menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = '10'
    [[menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = '20'
    [[menus.main]]
        name = 'Contact'
        pageRef = '/contact'
        weight = '30'
    